# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: skycoin
    name: skywire

  draft: true

before:
  hooks:
    - go mod tidy
builds:
  - id: skywire-visor-systray-darwin
    binary: skywire-visor
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - systray
    env:
      - CGO_ENABLED=1
    main: ./cmd/skywire-visor/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-visor-systray-windows
    binary: skywire-visor
    goos:
      - windows
    goarch:
      - amd64
    tags:
      - systray
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-visor/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-visor-systray-linux
    binary: skywire-visor
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
    tags:
      - systray
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-visor/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-cli-systray
    binary: skywire-cli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-cli/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}
  
  - id: skywire-cli-systray-windows
    binary: skywire-cli
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-cli/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}
  
  - id: skychat-systray
    binary: apps/skychat
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skychat/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}
  
  - id: skysocks-systray
    binary: apps/skysocks
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skysocks/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: skysocks-client-systray
    binary: apps/skysocks-client
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skysocks-client/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: vpn-server-systray
    binary: apps/vpn-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/vpn-server/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: vpn-client-systray
    binary: apps/vpn-client
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore: 
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/vpn-client/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: vpn-client-systray-windows
    binary: apps/vpn-client
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/vpn-client/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}


archives:
  - id: systray
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-systray-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
    builds:
      - skywire-visor-systray-linux
      - skywire-visor-systray-darwin
      - skywire-cli-systray
      - skysocks-systray
      - skysocks-client-systray
      - skychat-systray
      - vpn-server-systray
      - vpn-client-systray
    allow_different_binary_count: true

  - id: systray-windows
    format: zip
    wrap_in_directory: false
    name_template: 'skywire-systray-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
    builds:
      - skywire-visor-systray-windows
      - skywire-cli-systray-windows
      - vpn-client-systray-windows
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
