sudo: required
language: go
go:
  # - "1.16.x" At minimum the code should run make check on the latest two go versions in the default linux environment provided by Travis.
  - "1.16.x"

dist: xenial

services:
  - docker

matrix:
  include:
    - os: linux
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8.3

before_install:
  - nvm install 14.15
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.42.0

install:
  - make dep

before_script:
  - ci_scripts/create-ip-aliases.sh

script:
  - make check
  - make install-deps-ui
  - make lint-ui
  - make build-ui
  - make build

deploy:
  - provider: script
    script: bash ./ci_scripts/docker-push.sh -t "$TRAVIS_BRANCH" -p
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: bash ./ci_scripts/docker-push.sh -t "$TRAVIS_BRANCH" -p
    on:
      branch: develop
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: make github-release
    on:
      tags: true
